server:
  port: 9500
spring:
  application:
    name: spring-cloud-eureka
eureka:
  instance:
    hostname: eureka-server  # eurekaʵ����������

  client:
    register-with-eureka: true #�����Լ�ע�ᵽeureka��
    fetch-registry: true #����eureka������ȡ�����ע����Ϣ
    service-url:
      defaultZone: http://eureka-server1:9501/eureka/
