server:
  port: 9501
spring:
  application:
    name: spring-cloud-eureka
eureka:
  instance:
    hostname: eureka-server1  # eureka实例的主机名
 
  client:
    register-with-eureka: true #不把自己注册到eureka上
    fetch-registry: true #不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://eureka-server:9500/eureka/
